/**
 * @file        rexglue/commands/init_command.cpp
 * @brief       Project initialization command implementation
 *
 * @copyright   Copyright (c) 2026 Tom Clay <tomc@tctechstuff.com>
 *              All rights reserved.
 *
 * @license     BSD 3-Clause License
 *              See LICENSE file in the project root for full license text.
 */

#include "init_command.h"
#include "template_utils.h"

#include <filesystem>
#include <fstream>

#include <rex/logging.h>
#include <rex/result.h>

namespace fs = std::filesystem;

namespace rexglue::cli {

using rex::Err;
using rex::Error;
using rex::ErrorCategory;
using rex::Ok;

namespace {

// Generate CMakeLists.txt content
std::string generate_cmakelists(const AppNameParts& names) {
  std::string content;

  content += "# " + names.snake_case + " - ReXGlue Recompiled Project\n";
  content += "#\n";
  content += "# This file is yours to edit. 'rexglue migrate' will NOT overwrite it.\n";
  content += "# SDK boilerplate lives in generated/rexglue.cmake.\n";
  content += "\n";
  content += "cmake_minimum_required(VERSION 3.25)\n";
  content += "project(" + names.snake_case + " LANGUAGES CXX)\n";
  content += "\n";
  content += "set(CMAKE_CXX_STANDARD 23)\n";
  content += "set(CMAKE_CXX_STANDARD_REQUIRED ON)\n";
  content += "\n";
  content += "include(generated/rexglue.cmake)\n";
  content += "\n";
  content += "# Sources\n";
  content += "set(" + names.upper_case + "_SOURCES\n";
  content += "    src/main.cpp\n";
  content += ")\n";
  content += "\n";
  content += "if(WIN32)\n";
  content +=
      "    add_executable(" + names.snake_case + " WIN32 ${" + names.upper_case + "_SOURCES})\n";
  content += "else()\n";
  content += "    add_executable(" + names.snake_case + " ${" + names.upper_case + "_SOURCES})\n";
  content += "endif()\n";
  content += "\n";
  content += "rexglue_setup_target(" + names.snake_case + ")\n";
  content += "\n";

  return content;
}

// Generate main.cpp content
std::string generate_main_cpp(const AppNameParts& names) {
  std::string class_name = names.pascal_case + "App";
  std::string content;

  content += "// " + names.snake_case + " - ReXGlue Recompiled Project\n";
  content += "//\n";
  content += "// This file is yours to edit. 'rexglue migrate' will NOT overwrite it.\n";
  content += "\n";
  content += "#include \"generated/" + names.snake_case + "_config.h\"\n";
  content += "#include \"generated/" + names.snake_case + "_init.h\"\n";
  content += "\n";
  content += "#include \"" + names.snake_case + "_app.h\"\n";
  content += "\n";
  content += "REX_DEFINE_APP(" + names.snake_case + ", " + class_name + "::Create)\n";

  return content;
}

// Generate config.toml content
std::string generate_config_toml(const AppNameParts& names) {
  std::string content;

  content += "# " + names.snake_case + " - ReXGlue Codegen Configuration\n";
  content += "# Generated by: rexglue init\n";
  content += "# See README.md for full configuration reference.\n";
  content += "\n";
  content += "project_name = \"" + names.snake_case + "\"\n";
  content += "file_path = \"assets/default.xex\"\n";
  content += "out_directory_path = \"generated\"\n";

  return content;
}

// Generate CMakePresets.json content (no vcpkg toolchain - SDK bundles all dependencies)
std::string generate_cmake_presets() {
  std::string content;

  content += "{\n";
  content += "    \"version\": 6,\n";
  content += "    \"cmakeMinimumRequired\": { \"major\": 3, \"minor\": 25, \"patch\": 0 },\n";
  content += "    \"configurePresets\": [\n";
  content += "        {\n";
  content += "            \"name\": \"windows-base\",\n";
  content += "            \"hidden\": true,\n";
  content += "            \"generator\": \"Ninja\",\n";
  content += "            \"binaryDir\": \"${sourceDir}/out/build/${presetName}\",\n";
  content += "            \"cacheVariables\": {\n";
  content += "                \"CMAKE_C_COMPILER\": \"clang\",\n";
  content += "                \"CMAKE_CXX_COMPILER\": \"clang++\"\n";
  content += "            },\n";
  content += "            \"condition\": {\n";
  content += "                \"type\": \"equals\",\n";
  content += "                \"lhs\": \"${hostSystemName}\",\n";
  content += "                \"rhs\": \"Windows\"\n";
  content += "            }\n";
  content += "        },\n";
  content += "        {\n";
  content += "            \"name\": \"linux-base\",\n";
  content += "            \"hidden\": true,\n";
  content += "            \"generator\": \"Ninja\",\n";
  content += "            \"binaryDir\": \"${sourceDir}/out/build/${presetName}\",\n";
  content += "            \"cacheVariables\": {\n";
  content += "                \"CMAKE_C_COMPILER\": \"clang-20\",\n";
  content += "                \"CMAKE_CXX_COMPILER\": \"clang++-20\"\n";
  content += "            },\n";
  content += "            \"condition\": {\n";
  content += "                \"type\": \"equals\",\n";
  content += "                \"lhs\": \"${hostSystemName}\",\n";
  content += "                \"rhs\": \"Linux\"\n";
  content += "            }\n";
  content += "        },\n";
  content += "        {\n";
  content += "            \"name\": \"win-amd64-debug\",\n";
  content += "            \"displayName\": \"Windows AMD64 Debug\",\n";
  content += "            \"inherits\": \"windows-base\",\n";
  content += "            \"cacheVariables\": { \"CMAKE_BUILD_TYPE\": \"Debug\" }\n";
  content += "        },\n";
  content += "        {\n";
  content += "            \"name\": \"win-amd64-release\",\n";
  content += "            \"displayName\": \"Windows AMD64 Release\",\n";
  content += "            \"inherits\": \"windows-base\",\n";
  content += "            \"cacheVariables\": { \"CMAKE_BUILD_TYPE\": \"Release\" }\n";
  content += "        },\n";
  content += "        {\n";
  content += "            \"name\": \"linux-amd64-debug\",\n";
  content += "            \"displayName\": \"Linux AMD64 Debug\",\n";
  content += "            \"inherits\": \"linux-base\",\n";
  content += "            \"cacheVariables\": { \"CMAKE_BUILD_TYPE\": \"Debug\" }\n";
  content += "        },\n";
  content += "        {\n";
  content += "            \"name\": \"linux-amd64-release\",\n";
  content += "            \"displayName\": \"Linux AMD64 Release\",\n";
  content += "            \"inherits\": \"linux-base\",\n";
  content += "            \"cacheVariables\": { \"CMAKE_BUILD_TYPE\": \"Release\" }\n";
  content += "        },\n";
  content += "        {\n";
  content += "            \"name\": \"win-amd64-relwithdebinfo\",\n";
  content += "            \"displayName\": \"Windows AMD64 RelWithDebInfo\",\n";
  content += "            \"inherits\": \"windows-base\",\n";
  content += "            \"cacheVariables\": { \"CMAKE_BUILD_TYPE\": \"RelWithDebInfo\" }\n";
  content += "        },\n";
  content += "        {\n";
  content += "            \"name\": \"linux-amd64-relwithdebinfo\",\n";
  content += "            \"displayName\": \"Linux AMD64 RelWithDebInfo\",\n";
  content += "            \"inherits\": \"linux-base\",\n";
  content += "            \"cacheVariables\": { \"CMAKE_BUILD_TYPE\": \"RelWithDebInfo\" }\n";
  content += "        }\n";
  content += "    ],\n";
  content += "    \"buildPresets\": [\n";
  content +=
      "        { \"name\": \"win-amd64-debug\", \"configurePreset\": \"win-amd64-debug\" },\n";
  content +=
      "        { \"name\": \"win-amd64-release\", \"configurePreset\": \"win-amd64-release\" },\n";
  content +=
      "        { \"name\": \"win-amd64-relwithdebinfo\", \"configurePreset\": "
      "\"win-amd64-relwithdebinfo\" },\n";
  content +=
      "        { \"name\": \"linux-amd64-debug\", \"configurePreset\": \"linux-amd64-debug\" },\n";
  content +=
      "        { \"name\": \"linux-amd64-release\", \"configurePreset\": \"linux-amd64-release\" "
      "},\n";
  content +=
      "        { \"name\": \"linux-amd64-relwithdebinfo\", \"configurePreset\": "
      "\"linux-amd64-relwithdebinfo\" }\n";
  content += "    ]\n";
  content += "}\n";

  return content;
}

}  // anonymous namespace

Result<void> InitProject(const InitOptions& opts, const CliContext& ctx) {
  (void)ctx;  // Currently unused

  // Validate required options
  if (opts.app_name.empty()) {
    return Err<void>(ErrorCategory::Config, "--app_name is required");
  }
  if (opts.app_root.empty()) {
    return Err<void>(ErrorCategory::Config, "--app_root is required");
  }

  // Validate and parse app name
  std::string validation_error;
  if (!validate_app_name(opts.app_name, validation_error)) {
    return Err<void>(ErrorCategory::Config, validation_error);
  }
  auto names = parse_app_name(opts.app_name);

  fs::path root = fs::absolute(opts.app_root);

  REXLOG_INFO("Initializing project '{}' at: {}", names.snake_case, root.string());
  REXLOG_INFO("Mode: {}", opts.sdk_example ? "SDK example" : "standalone");

  // Check if directory exists and has contents
  if (fs::exists(root)) {
    if (!fs::is_directory(root)) {
      return Err<void>(ErrorCategory::IO, "Path exists but is not a directory: " + root.string());
    }

    bool has_contents = false;
    for (const auto& entry : fs::directory_iterator(root)) {
      (void)entry;
      has_contents = true;
      break;
    }

    if (has_contents && !opts.force) {
      return Err<void>(ErrorCategory::IO,
                       "Directory is not empty. Use --force to overwrite: " + root.string());
    }
  }

  // Create directory structure
  REXLOG_INFO("Creating directory structure...");

  std::error_code ec;
  fs::create_directories(root, ec);
  if (ec) {
    return Err<void>(ErrorCategory::IO, "Failed to create root directory: " + ec.message());
  }

  fs::create_directories(root / "src", ec);
  if (ec) {
    return Err<void>(ErrorCategory::IO, "Failed to create src directory: " + ec.message());
  }

  fs::create_directories(root / "generated", ec);
  if (ec) {
    return Err<void>(ErrorCategory::IO, "Failed to create generated directory: " + ec.message());
  }

  // Generate files
  REXLOG_INFO("Generating project files...");

  if (!write_file(root / "CMakeLists.txt", generate_cmakelists(names))) {
    return Err<void>(ErrorCategory::IO, "Failed to write CMakeLists.txt");
  }
  REXLOG_DEBUG("  Created CMakeLists.txt");

  // generated/rexglue.cmake (SDK-managed)
  if (!write_file(root / "generated" / "rexglue.cmake", generate_rexglue_cmake(names))) {
    return Err<void>(ErrorCategory::IO, "Failed to write generated/rexglue.cmake");
  }
  REXLOG_DEBUG("  Created generated/rexglue.cmake");

  if (!write_file(root / "src" / "main.cpp", generate_main_cpp(names))) {
    return Err<void>(ErrorCategory::IO, "Failed to write main.cpp");
  }
  REXLOG_DEBUG("  Created src/main.cpp");

  // src/{name}_app.h (user-owned)
  std::string app_header_filename = names.snake_case + "_app.h";
  if (!write_file(root / "src" / app_header_filename, generate_app_header(names))) {
    return Err<void>(ErrorCategory::IO, "Failed to write src/" + app_header_filename);
  }
  REXLOG_DEBUG("  Created src/{}", app_header_filename);

  std::string config_filename = names.snake_case + "_config.toml";
  if (!write_file(root / config_filename, generate_config_toml(names))) {
    return Err<void>(ErrorCategory::IO, "Failed to write config.toml");
  }
  REXLOG_DEBUG("  Created {}", config_filename);

  if (!write_file(root / "CMakePresets.json", generate_cmake_presets())) {
    return Err<void>(ErrorCategory::IO, "Failed to write CMakePresets.json");
  }
  REXLOG_DEBUG("  Created CMakePresets.json");

  // Print success message with next steps
  REXLOG_INFO("Project '{}' initialized in '{}' successfully!", names.snake_case, opts.app_root);

  return Ok();
}

}  // namespace rexglue::cli
