/**
 * @file        rexglue/commands/migrate_command.cpp
 * @brief       Project migration command implementation
 *
 * @copyright   Copyright (c) 2026 Tom Clay <tomc@tctechstuff.com>
 * @license     BSD 3-Clause License
 */

#include "migrate_command.h"
#include "template_utils.h"

#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>

#include <rex/codegen/config.h>
#include <rex/logging.h>
#include <rex/result.h>

namespace fs = std::filesystem;

namespace rexglue::cli {

using rex::Err;
using rex::ErrorCategory;
using rex::Ok;
using rex::Result;
namespace {

// Same generators as init — produces the current SDK template.
// These are duplicated from init_command.cpp intentionally so that
// migrate and init can evolve independently if needed.

std::string generate_main_cpp(const AppNameParts& names) {
  std::string class_name = names.pascal_case + "App";
  std::string content;

  content += "// " + names.snake_case + " - ReXGlue Recompiled Project\n";
  content += "// Generated by: rexglue migrate\n";
  content += "//\n";
  content += "// This file is SDK-managed. Customizations go in virtual hook overrides.\n";
  content += "// Running 'rexglue migrate' will overwrite this file.\n";
  content += "\n";
  content += "#include \"generated/" + names.snake_case + "_config.h\"\n";
  content += "#include \"generated/" + names.snake_case + "_init.h\"\n";
  content += "\n";
  content += "#include <rex/rex_app.h>\n";
  content += "\n";
  content += "class " + class_name + " : public rex::ReXApp {\n";
  content += " public:\n";
  content += "  using rex::ReXApp::ReXApp;\n";
  content += "\n";
  content += "  static std::unique_ptr<rex::ui::WindowedApp> Create(\n";
  content += "      rex::ui::WindowedAppContext& ctx) {\n";
  content += "    return std::unique_ptr<" + class_name + ">(new " + class_name + "(ctx, \"" +
             names.snake_case + "\",\n";
  content += "        PPCImageConfig));\n";
  content += "  }\n";
  content += "};\n";
  content += "\n";
  content += "REX_DEFINE_APP(" + names.snake_case + ", " + class_name + "::Create)\n";

  return content;
}

std::string generate_cmakelists(const AppNameParts& names) {
  std::string content;

  content += "# " + names.snake_case + " - ReXGlue Recompiled Project\n";
  content += "# Generated by: rexglue migrate\n";
  content += "#\n";
  content += "# This file is SDK-managed. Running 'rexglue migrate' will overwrite it.\n";
  content += "\n";
  content += "cmake_minimum_required(VERSION 3.25)\n";
  content += "project(" + names.snake_case + " LANGUAGES CXX)\n";
  content += "\n";
  content += "set(CMAKE_CXX_STANDARD 23)\n";
  content += "set(CMAKE_CXX_STANDARD_REQUIRED ON)\n";
  content += "\n";
  content += "set(REXSDK_DIR \"\" CACHE PATH \"Path to rexglue-sdk source tree\")\n";
  content += "if(REXSDK_DIR)\n";
  content += "    add_subdirectory(\"${REXSDK_DIR}\" rexglue-sdk)\n";
  content += "else()\n";
  content += "    find_package(rexglue QUIET CONFIG)\n";
  content += "    if(NOT rexglue_FOUND)\n";
  content += "        message(FATAL_ERROR\n";
  content += "            \"ReXGlue SDK not found. Either:\\n\"\n";
  content +=
      "            \"  - Set REXSDK_DIR to the rexglue-sdk source tree (e.g. "
      "thirdparty/rexglue-sdk)\\n\"\n";
  content += "            \"  - Install the SDK package and ensure it is on CMAKE_PREFIX_PATH\")\n";
  content += "    endif()\n";
  content += "endif()\n";
  content += "\n";
  content += "# Sources\n";
  content += "set(" + names.upper_case + "_SOURCES\n";
  content += "    src/main.cpp\n";
  content += ")\n";
  content += "\n";
  content += "# Include generated code if codegen has been run\n";
  content += "if(EXISTS \"${CMAKE_CURRENT_SOURCE_DIR}/generated/sources.cmake\")\n";
  content += "    include(generated/sources.cmake)\n";
  content += "    list(APPEND " + names.upper_case + "_SOURCES ${GENERATED_SOURCES})\n";
  content += "endif()\n";
  content += "\n";
  content += "if(WIN32)\n";
  content +=
      "    add_executable(" + names.snake_case + " WIN32 ${" + names.upper_case + "_SOURCES})\n";
  content += "else()\n";
  content += "    add_executable(" + names.snake_case + " ${" + names.upper_case + "_SOURCES})\n";
  content += "endif()\n";
  content += "\n";
  content += "target_include_directories(" + names.snake_case + " PRIVATE\n";
  content += "    ${CMAKE_CURRENT_SOURCE_DIR}\n";
  content += "    ${CMAKE_CURRENT_SOURCE_DIR}/generated\n";
  content += ")\n";
  content += "\n";
  content += "target_link_libraries(" + names.snake_case + " PRIVATE\n";
  content += "    rex::core\n";
  content += "    rex::system\n";
  content += "    rex::kernel\n";
  content += "    rex::graphics\n";
  content += "    rex::ui\n";
  content += ")\n";
  content += "\n";
  content += "# Platform entry point, ReXApp source, and platform-specific settings\n";
  content += "rexglue_configure_target(" + names.snake_case + ")\n";
  content += "\n";
  content += "# Codegen target - run 'cmake --build . --target " + names.snake_case + "_codegen'\n";
  content += "add_custom_target(" + names.snake_case + "_codegen\n";
  content += "    COMMAND $<TARGET_FILE:rex::rexglue> codegen ${CMAKE_CURRENT_SOURCE_DIR}/" +
             names.snake_case + "_config.toml\n";
  content += "    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}\n";
  content += "    COMMENT \"Generating recompiled code for " + names.snake_case + "\"\n";
  content += "    VERBATIM\n";
  content += ")\n";

  return content;
}

std::string read_file_content(const fs::path& path) {
  std::ifstream file(path);
  if (!file)
    return {};
  std::ostringstream ss;
  ss << file.rdbuf();
  return ss.str();
}

}  // anonymous namespace

Result<void> MigrateProject(const MigrateOptions& opts, const CliContext& ctx) {
  (void)ctx;

  if (opts.app_root.empty()) {
    return Err<void>(ErrorCategory::Config, "--app_root is required");
  }

  fs::path root = fs::absolute(opts.app_root);

  // Validate that this looks like an existing rexglue project
  if (!fs::exists(root)) {
    return Err<void>(ErrorCategory::IO, "Project directory does not exist: " + root.string());
  }
  if (!fs::exists(root / "src" / "main.cpp")) {
    return Err<void>(ErrorCategory::IO,
                     "Not a rexglue project (no src/main.cpp): " + root.string());
  }

  // Find the *_config.toml to read the project name
  fs::path config_path;
  for (const auto& entry : fs::directory_iterator(root)) {
    if (entry.is_regular_file() && entry.path().extension() == ".toml" &&
        entry.path().stem().string().ends_with("_config")) {
      config_path = entry.path();
      break;
    }
  }
  if (config_path.empty()) {
    return Err<void>(ErrorCategory::IO, "No *_config.toml found in project root: " + root.string());
  }

  // Read project name from config
  rex::codegen::RecompilerConfig config;
  config.Load(config_path.string());
  if (config.projectName.empty() || config.projectName == "rex") {
    return Err<void>(ErrorCategory::Config,
                     "Could not read project_name from " + config_path.filename().string());
  }

  auto names = parse_app_name(config.projectName);

  // Check which files will be modified and warn if they differ from the template
  std::string new_main = generate_main_cpp(names);
  std::string new_cmake = generate_cmakelists(names);
  std::string old_main = read_file_content(root / "src" / "main.cpp");
  std::string old_cmake = read_file_content(root / "CMakeLists.txt");

  std::vector<std::string> modified_files;
  if (old_main != new_main)
    modified_files.push_back("src/main.cpp");
  if (old_cmake != new_cmake)
    modified_files.push_back("CMakeLists.txt");

  if (modified_files.empty()) {
    REXLOG_INFO("Project '{}' is already up to date.", names.snake_case);
    return Ok();
  }

  if (!opts.force) {
    std::cerr << "The following files will be overwritten:\n";
    for (const auto& f : modified_files) {
      std::cerr << "  " << f << "\n";
    }
    std::cerr << "\nAny local changes to these files will be lost.\n";
    std::cerr << "Continue? [y/N] " << std::flush;

    std::string answer;
    std::getline(std::cin, answer);
    if (answer.empty() || (answer[0] != 'y' && answer[0] != 'Y')) {
      REXLOG_INFO("Migration cancelled.");
      return Ok();
    }
  }

  REXLOG_INFO("Migrating project '{}' at: {}", names.snake_case, root.string());

  // Overwrite src/main.cpp
  if (old_main != new_main) {
    if (!write_file(root / "src" / "main.cpp", new_main)) {
      return Err<void>(ErrorCategory::IO, "Failed to write src/main.cpp");
    }
    REXLOG_INFO("  Overwrote src/main.cpp");
  }

  // Overwrite CMakeLists.txt
  if (old_cmake != new_cmake) {
    if (!write_file(root / "CMakeLists.txt", new_cmake)) {
      return Err<void>(ErrorCategory::IO, "Failed to write CMakeLists.txt");
    }
    REXLOG_INFO("  Overwrote CMakeLists.txt");
  }

  REXLOG_INFO("Migration complete. Re-run CMake configure to pick up changes.");

  return Ok();
}

}  // namespace rexglue::cli
