/**
 * @file        rexglue/commands/template_utils.h
 * @brief       Shared utilities for init and migrate commands
 *
 * @copyright   Copyright (c) 2026 Tom Clay <tomc@tctechstuff.com>
 * @license     BSD 3-Clause License
 */

#pragma once

#include <algorithm>
#include <cctype>
#include <filesystem>
#include <fstream>
#include <string>
#include <vector>

#include <rex/logging.h>

namespace rexglue::cli {

struct AppNameParts {
  std::string snake_case;
  std::string pascal_case;
  std::string upper_case;
};

inline bool validate_app_name(const std::string& input, std::string& error) {
  if (input.empty()) {
    error = "App name must not be empty";
    return false;
  }
  if (!std::isalpha(static_cast<unsigned char>(input[0]))) {
    error = "App name must start with a letter";
    return false;
  }
  for (char c : input) {
    if (!std::isalnum(static_cast<unsigned char>(c)) && c != '_' && c != '-' && c != ' ') {
      error = "App name contains invalid character '" + std::string(1, c) +
              "'. Only alphanumeric, space, underscore, and dash are allowed";
      return false;
    }
  }
  return true;
}

inline AppNameParts parse_app_name(const std::string& input) {
  std::vector<std::string> words;
  std::string current;
  for (char c : input) {
    if (c == ' ' || c == '_' || c == '-') {
      if (!current.empty()) {
        words.push_back(current);
        current.clear();
      }
    } else {
      current += static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
    }
  }
  if (!current.empty()) {
    words.push_back(current);
  }

  AppNameParts parts;
  for (size_t i = 0; i < words.size(); ++i) {
    if (i > 0)
      parts.snake_case += '_';
    parts.snake_case += words[i];
  }
  for (const auto& w : words) {
    std::string word = w;
    if (!word.empty() && std::isalpha(static_cast<unsigned char>(word[0]))) {
      word[0] = static_cast<char>(std::toupper(static_cast<unsigned char>(word[0])));
    }
    parts.pascal_case += word;
  }
  for (const auto& w : words) {
    for (char c : w) {
      parts.upper_case += static_cast<char>(std::toupper(static_cast<unsigned char>(c)));
    }
  }
  return parts;
}

inline bool write_file(const std::filesystem::path& path, const std::string& content) {
  std::ofstream file(path);
  if (!file) {
    REXLOG_ERROR("Failed to create file: {}", path.string());
    return false;
  }
  file << content;
  return true;
}

inline std::string generate_rexglue_cmake(const AppNameParts& names) {
  std::string content;

  content += "# Auto-generated by rexglue - DO NOT EDIT\n";
  content += "# This file is regenerated by 'rexglue migrate'.\n";
  content += "\n";
  content += "# Find SDK\n";
  content += "set(REXSDK_DIR \"\" CACHE PATH \"Path to rexglue-sdk source tree\")\n";
  content += "if(REXSDK_DIR)\n";
  content += "    add_subdirectory(\"${REXSDK_DIR}\" rexglue-sdk)\n";
  content += "else()\n";
  content += "    find_package(rexglue QUIET CONFIG)\n";
  content += "    if(NOT rexglue_FOUND)\n";
  content += "        message(FATAL_ERROR\n";
  content += "            \"ReXGlue SDK not found. Either:\\n\"\n";
  content +=
      "            \"  - Set REXSDK_DIR to the rexglue-sdk source tree (e.g. "
      "thirdparty/rexglue-sdk)\\n\"\n";
  content += "            \"  - Install the SDK package and ensure it is on CMAKE_PREFIX_PATH\")\n";
  content += "    endif()\n";
  content += "endif()\n";
  content += "\n";
  content += "# Include generated code if codegen has been run\n";
  content += "if(EXISTS \"${CMAKE_CURRENT_SOURCE_DIR}/generated/sources.cmake\")\n";
  content += "    include(generated/sources.cmake)\n";
  content += "endif()\n";
  content += "\n";
  content += "# Configure a rexglue target with SDK libraries and platform settings.\n";
  content += "# Call after add_executable() in your CMakeLists.txt.\n";
  content += "# Usage: rexglue_setup_target(<target>)\n";
  content += "macro(rexglue_setup_target target_name)\n";
  content += "    target_sources(${target_name} PRIVATE ${GENERATED_SOURCES})\n";
  content += "    target_include_directories(${target_name} PRIVATE\n";
  content += "        ${CMAKE_CURRENT_SOURCE_DIR}\n";
  content += "        ${CMAKE_CURRENT_SOURCE_DIR}/src\n";
  content += "        ${CMAKE_CURRENT_SOURCE_DIR}/generated\n";
  content += "    )\n";
  content += "    target_link_libraries(${target_name} PRIVATE\n";
  content += "        rex::core\n";
  content += "        rex::system\n";
  content += "        rex::kernel\n";
  content += "        rex::graphics\n";
  content += "        rex::ui\n";
  content += "    )\n";
  content += "    rexglue_configure_target(${target_name})\n";
  content += "endmacro()\n";
  content += "\n";
  content += "# Codegen target - run 'cmake --build . --target " + names.snake_case + "_codegen'\n";
  content += "add_custom_target(" + names.snake_case + "_codegen\n";
  content += "    COMMAND $<TARGET_FILE:rex::rexglue> codegen ${CMAKE_CURRENT_SOURCE_DIR}/" +
             names.snake_case + "_config.toml\n";
  content += "    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}\n";
  content += "    COMMENT \"Generating recompiled code for " + names.snake_case + "\"\n";
  content += "    VERBATIM\n";
  content += ")\n";

  return content;
}

inline std::string generate_app_header(const AppNameParts& names) {
  std::string class_name = names.pascal_case + "App";
  std::string content;

  content += "// " + names.snake_case + " - ReXGlue Recompiled Project\n";
  content += "//\n";
  content += "// This file is yours to edit. 'rexglue migrate' will NOT overwrite it.\n";
  content += "// Customize your app by overriding virtual hooks from rex::ReXApp.\n";
  content += "\n";
  content += "#pragma once\n";
  content += "\n";
  content += "#include <rex/rex_app.h>\n";
  content += "\n";
  content += "class " + class_name + " : public rex::ReXApp {\n";
  content += " public:\n";
  content += "  using rex::ReXApp::ReXApp;\n";
  content += "\n";
  content += "  static std::unique_ptr<rex::ui::WindowedApp> Create(\n";
  content += "      rex::ui::WindowedAppContext& ctx) {\n";
  content += "    return std::unique_ptr<" + class_name + ">(new " + class_name + "(ctx, \"" +
             names.snake_case + "\",\n";
  content += "        PPCImageConfig));\n";
  content += "  }\n";
  content += "\n";
  content += "  // Override virtual hooks for customization:\n";
  content += "  // void OnPreSetup(rex::RuntimeConfig& config) override {}\n";
  content += "  // void OnPostSetup() override {}\n";
  content += "  // void OnCreateDialogs(rex::ui::ImGuiDrawer* drawer) override {}\n";
  content += "  // void OnShutdown() override {}\n";
  content += "  // void OnConfigurePaths(rex::PathConfig& paths) override {}\n";
  content += "};\n";

  return content;
}

}  // namespace rexglue::cli
